### ISSUE TITLE
lisp-journey is you?? Did it have to be so obscure?!

### ISSUE THREAD

**Issue by Hexstream** [vindarel/lisp-journey#6]
Hello,

I've had a hell of a hard time figuring out that `lisp-journey == vindarel`.

This makes no sense to me, why does https://lisp-journey.gitlab.io/about/ have to be so useless?? Why is your online presence so unintegrated?

I understand that some people "silo" some stuff for privacy reasons, but you don't seem to be doing that since you're openly hosting this repo here... I really don't understand your strategy...

**Comment by vindarel** [comment]
Hello,
ahah :) 
True that the About page doesn't say who I am ! I should add it. What would that have changed for you ?

True also that I don't have an integrated online presence. I'm mostly active on reddit, where I post those blog posts, which for most of them go into the Cookbook anyway.
I don't have a strategy to bring attention to myself or to my blog, what I want to do is improve the online resources, mostly for newcomers. So I mostly do this on the cookbook and the awesome-cl list. 
Another not integrated thing is my old reddit nickname that is "dzecniv"… (there's a part of "vincent" there). (Did you notice ? Some did.) Years ago I wanted to silo my reddit account, indeed, but that is not the case anymore. 

But is that important somewhat ?

thanks for the note

**Comment by Hexstream** [comment]
Cool! To me that makes a big difference, the Common Lisp community is already unintegrated enough as it is...

Somehow, I find "Vindarel made the lisp-journey blog and contributed to some other nice stuff" much more exciting than "Someone made the lisp-journey blog, but nobody really knows who that is, they seem to want to stay private, and unrelatedly there's also Vindarel who contributed to some nice stuff"...

I think a Common Lisp continent would be better than a random bunch of Common Lisp islands...

As nice as "everyone is equal anyway" might sound as a concept, cognitively I find it easier to value people for their contributions when I *know* what their contributions are... I don't know how useful misguided selflessness is... And I certainly find it easier to value contributions when I know that there's some sort of identifiable person behind it, that it's not just floating there in a vacuum...

Not sure if this makes any kind of sense? ;P

PS: Nice commit, https://lisp-journey.gitlab.io/about/ will update later I guess?

**Comment by vindarel** [comment]
> Not sure if this makes any kind of sense?

Yes totally, thanks for explaining, I understand and I agree ! \o/ 

(updated. I hadn't pushed to gitlab given this is a github issue^^)

**Comment by Hexstream** [comment]
Probably also consider linking to https://lisp-journey.gitlab.io/ from [your profile](https://github.com/vindarel). :)

**Comment by vindarel** [comment]
and done, thanks.

**Comment by jmercouris** [comment]
@Hexstream allow people to have their freedom how they will it.

**Comment by Hexstream** [comment]
I am! Please note the following:

1. He seems to be agreeing with me;
2. I have merely made suggestions, using wording such as `consider`;
3. In my first two posts in this thread on March 16, I told him about how everyone might benefit if he had a bit more integration in his online presence. I did not even suggest that he should reveal his (actual or apparent) real name, yet "coincidentally" *the next day* he [submitted](https://www.reddit.com/r/lisp/comments/b1dmjm/these_years_in_common_lisp_2018_nonmedium_link_in/) his "new" (slightly reworked) post and that has is (actual or apparent) real name, which as far as I know, was the first such occurrence.

So I might speculate that my comments have been welcome and fruitful. In saying `Probably also consider linking to https://lisp-journey.gitlab.io/ from your profile. :)`, I was merely pointing out a potential omission. In short, I think you're overreacting. And now, I've had to post this awkward explanation in defense. I hope you're happy. ;P

**Comment by vindarel** [comment]
It's cool, this thread was fruitful.

**Comment by Hexstream** [comment]
Thank you very much for confirming it!
